server:
    port: 8080

spring:
    profiles:
        active: dev
    data:
        mongodb:
            uri: mongodb://localhost/springAssignment
            database: springAssignment
            host: localhost
            port: 27017

logging:
    level:
        root: WARN
        org.springframework: debug
        org.springframework.web: debug
        org.springframework.security: debug

spring:
  thymeleaf:
    cache: false